'use client'

import { useEffect, useState } from 'react'
import { Activity, Box, ExternalLink, FileImage, LayoutDashboard, MessageSquareText, PackageSearch, Plus, Save, Settings, Share2, Trash2, Users, X } from 'lucide-react'
import Link from 'next/link'

type Collection = 'categories' | 'products' | 'contacts' | 'socials' | 'sections' | 'heroSlides' | 'articles' | 'faqs' | 'rfqs'
type View = Collection | 'settings' | 'dashboard' | 'users' | 'audit'
type Item = Record<string, any> & { id: number }
type AdminUser = { id: number; email: string; name: string; role: 'ADMIN' | 'EDITOR' | 'RFQ_OPERATOR'; active: boolean; createdAt: string; updatedAt: string }
type Dashboard = { user: { id: number; email: string; name: string; role: AdminUser['role'] }; counts: { categories: number; products: number; articles: number; openRfqs: number }; recentRfqs: Array<{ id: number; reference: string; company: string; status: string; createdAt: string }> }

const nav: Array<{ key: View; label: string; icon: any }> = [
  { key: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { key: 'settings', label: 'Site settings', icon: Settings }, { key: 'categories', label: 'Product categories', icon: Box }, { key: 'products', label: 'Products', icon: PackageSearch }, { key: 'contacts', label: 'Customer contacts', icon: MessageSquareText }, { key: 'socials', label: 'Social links', icon: Share2 }, { key: 'heroSlides', label: 'Hero slides', icon: FileImage }, { key: 'sections', label: 'Page sections & images', icon: FileImage }, { key: 'articles', label: 'Resources', icon: FileImage }, { key: 'faqs', label: 'FAQ', icon: MessageSquareText }, { key: 'rfqs', label: 'RFQ inbox', icon: PackageSearch }, { key: 'users', label: 'Users', icon: Users }, { key: 'audit', label: 'Audit log', icon: Activity }
]
const contentCollections = new Set<Collection>(['categories', 'products', 'contacts', 'socials', 'sections', 'heroSlides', 'articles', 'faqs'])
const imageKeys = new Set(['imageUrl', 'coverImageUrl', 'mobileImageUrl'])
const defaults: Record<Collection, Record<string, any>> = {
  categories: { name: 'New category', line: 'Reagents', description: '', imageUrl: '', sortOrder: 0, status: 'DRAFT' }, products: { name: 'New product', categoryId: 1, brand: '', catNo: '', specification: '', temperature: 'Ambient', imageUrl: '', status: 'DRAFT' }, contacts: { type: 'Phone', label: 'Customer service', value: '', href: '', enabled: true, sortOrder: 0 }, socials: { platform: 'VK', url: 'https://vk.com/', displayValue: '', imageUrl: '', enabled: true, sortOrder: 0 }, heroSlides: { kicker: '', title: 'New hero slide', body: '', imageUrl: '/hero-lab.jpg', mobileImageUrl: '', focalPoint: '50% 50%', ctaLabel: 'Request a quote', ctaHref: '/rfq', enabled: true, status: 'DRAFT', sortOrder: 0 }, sections: { pageKey: 'home', sectionKey: 'new-section', title: 'New section', body: '', ctaLabel: '', ctaHref: '', imageUrl: '', enabled: true, status: 'DRAFT', sortOrder: 0 }, articles: { topic: 'Procurement', title: 'New guide', slug: 'new-guide', summary: '', body: '', coverImageUrl: '', reviewer: 'Zehongyan Technical & Supply Team', status: 'DRAFT' }, faqs: { topic: 'General', question: 'New question', answer: '', enabled: true, sortOrder: 0 }, rfqs: { status: 'IN_REVIEW' }
}

export default function AdminPage() {
  const [active, setActive] = useState<View>('dashboard'); const [items, setItems] = useState<Item[]>([]); const [selected, setSelected] = useState<Item | null>(null); const [status, setStatus] = useState('Ready'); const [rfqFilter, setRfqFilter] = useState(''); const [settings, setSettings] = useState({ siteName: 'Zehongyan Biotech', siteNameZh: 'Zehongyan Biotech', siteNameRu: 'Zehongyan Biotech', logoUrl: '/hocore-logo.jpg', faviconUrl: '', defaultLocale: 'en' }); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [audit, setAudit] = useState<any>(null); const [error, setError] = useState('')
  // The active view is the fetch boundary; loaders intentionally remain local to this client shell.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { setError(''); if (active === 'dashboard') { void loadDashboard(); return } if (active === 'settings') { void loadSettings(); return } if (active === 'users') { void loadUsers(); return } if (active === 'audit') { void loadAudit(); return } if (active === 'rfqs' || contentCollections.has(active as Collection)) void loadCollection(active as Collection) }, [active, rfqFilter])
  async function parseResponse(response: Response) { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed'); return data }
  async function loadDashboard() { try { setDashboard(await parseResponse(await fetch('/api/admin/dashboard'))) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load dashboard') } }
  async function loadSettings() { try { setSettings(await parseResponse(await fetch('/api/admin/settings'))) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load settings') } }
  async function loadUsers() { try { const data = await parseResponse(await fetch('/api/admin/users')); setItems(data); setSelected(data[0] ?? null) } catch (e) { setItems([]); setSelected(null); setError(e instanceof Error ? e.message : 'Unable to load users') } }
  async function loadAudit() { try { setAudit(await parseResponse(await fetch('/api/admin/audit?pageSize=50'))) } catch (e) { setAudit(null); setError(e instanceof Error ? e.message : 'Unable to load audit log') } }
  async function loadCollection(collection: Collection) { try { const endpoint = collection === 'rfqs' ? `/api/admin/rfq${rfqFilter ? `?status=${encodeURIComponent(rfqFilter)}` : ''}` : `/api/admin/content?collection=${collection}`; const data = await parseResponse(await fetch(endpoint)); setItems(data); setSelected(data[0] ?? null) } catch (e) { setItems([]); setSelected(null); setError(e instanceof Error ? e.message : 'Unable to load records') } }
  async function save() { setStatus('Saving…'); setError(''); try { if (active === 'settings') { setSettings(await parseResponse(await fetch('/api/admin/settings', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(settings) }))); setStatus('Published'); return } if (active === 'users' && selected) { const { id, password, email, name, role, active: userActive } = selected; const data = { email, name, role, active: userActive, ...(password ? { password } : {}) }; const response = await fetch('/api/admin/users', { method: id ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(id ? { id, ...data } : data) }); const updated = await parseResponse(response); setItems((current) => id ? current.map((item) => item.id === id ? updated : item) : [...current, updated]); setSelected(updated); setStatus('Saved'); return } if (active === 'rfqs' && selected) { const { id, ...data } = selected; const updated = await parseResponse(await fetch('/api/admin/rfq', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id, data, status: data.status }) })); setItems((current) => current.map((item) => item.id === id ? updated : item)); setSelected(updated); setStatus('Published'); return } if (!selected || !contentCollections.has(active as Collection)) return; const { id, ...data } = selected; const updated = await parseResponse(await fetch('/api/admin/content', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ collection: active, id, data }) })); setItems((current) => current.map((item) => item.id === id ? updated : item)); setSelected(updated); setStatus('Published') } catch (e) { setStatus('Save failed'); setError(e instanceof Error ? e.message : 'Unable to save') } }
  async function add() { setError(''); if (active === 'users') { setSelected({ id: 0, email: '', name: '', role: 'EDITOR', active: true, password: '' }); setStatus('New user'); return } if (!contentCollections.has(active as Collection)) return; try { const created = await parseResponse(await fetch('/api/admin/content', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ collection: active, data: defaults[active as Collection] }) })); setItems((current) => [...current, created]); setSelected(created); setStatus('Draft created') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create record') } }
  async function remove() { if (!selected || !contentCollections.has(active as Collection) || !confirm('Delete this item?')) return; try { await parseResponse(await fetch('/api/admin/content', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ collection: active, id: selected.id }) })); const next = items.filter((item) => item.id !== selected.id); setItems(next); setSelected(next[0] ?? null); setStatus('Deleted') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete record') } }
  async function logout() { await fetch('/api/admin/logout', { method: 'POST' }); window.location.href = '/admin/login' }
  const activeLabel = nav.find((item) => item.key === active)?.label || 'Site settings'
  return <main className="admin-app"><aside className="admin-sidebar"><Link className="admin-brand" href="/"><span>Z</span><div>Zehongyan<small>BIOTECH ADMIN</small></div></Link><nav>{nav.map((entry) => { const Icon = entry.icon; return <button key={entry.key} className={active === entry.key ? 'active' : ''} onClick={() => setActive(entry.key)}><Icon />{entry.label}</button> })}</nav><div className="admin-user"><strong>{dashboard?.user.name || 'Site Administrator'}</strong><span>{dashboard?.user.email || 'admin@hocore.bio'}</span><span className="admin-role">{dashboard?.user.role || 'ADMIN'}</span><button className="admin-logout" onClick={logout}>Sign out</button></div></aside><section className="admin-main"><header className="admin-topbar"><div><span>Content management</span><strong>{activeLabel}</strong></div><div><span className="save-status">{status}</span><a className="admin-preview" href="/en" target="_blank" rel="noreferrer">Preview site <ExternalLink /></a>{active !== 'dashboard' && active !== 'audit' && <button className="admin-save" onClick={save}><Save />Save changes</button>}</div></header>{error && <div className="admin-alert" role="alert"><span>{error}</span><button onClick={() => setError('')} aria-label="Dismiss"><X size={15} /></button></div>}{active === 'dashboard' ? <DashboardView data={dashboard} /> : active === 'settings' ? <SettingsEditor value={settings} onChange={setSettings} /> : active === 'users' ? <CollectionView title="Users" items={items} selected={selected} onSelect={setSelected} onAdd={add} editor={selected ? <UserEditor item={selected} onChange={setSelected} /> : null} actions={null} /> : active === 'audit' ? <AuditView data={audit} /> : <CollectionView title={activeLabel} items={items} selected={selected} onSelect={setSelected} onAdd={active === 'rfqs' ? undefined : add} onDelete={active === 'rfqs' ? undefined : remove} filter={active === 'rfqs' ? <select value={rfqFilter} onChange={(e) => setRfqFilter(e.target.value)}><option value="">Open RFQs</option><option value="NEW">New</option><option value="IN_REVIEW">In review</option><option value="QUOTED">Quoted</option><option value="WON">Won</option><option value="LOST">Lost</option><option value="SPAM">Spam</option><option value="ARCHIVED">Archived</option></select> : null} editor={selected ? (active === 'rfqs' ? <RfqEditor item={selected} onChange={setSelected} onStatus={setStatus} /> : <ItemEditor item={selected} onChange={setSelected} />) : null} actions={selected ? <><button className="delete-button" onClick={remove} disabled={active === 'rfqs'}><Trash2 />Delete</button><button className="admin-save" onClick={save}><Save />Save changes</button></> : null} />}</section></main>
}

function DashboardView({ data }: { data: Dashboard | null }) { if (!data) return <div className="dashboard-content"><div className="admin-empty">Loading dashboard…</div></div>; const cards = [{ label: 'Product categories', value: data.counts.categories }, { label: 'Products', value: data.counts.products }, { label: 'Resource articles', value: data.counts.articles }, { label: 'Open RFQs', value: data.counts.openRfqs }]; return <div className="dashboard-content"><div className="dashboard-welcome"><div><span className="admin-eyebrow">Workspace overview</span><h1>Good to see you, {data.user.name}.</h1><p>Manage the catalogue, sourcing pages and enquiry workflow from one place.</p></div><a className="admin-save" href="/en/rfq" target="_blank" rel="noreferrer">Open RFQ form <ExternalLink size={14} /></a></div><div className="dashboard-stats">{cards.map((card) => <div key={card.label}><span>{card.label}</span><strong>{card.value}</strong></div>)}</div><div className="dashboard-panel"><div className="panel-heading"><div><span className="admin-eyebrow">Latest activity</span><h2>Recent enquiries</h2></div></div>{data.recentRfqs.length ? <div className="dashboard-table"><div className="table-row table-head"><span>Reference</span><span>Company</span><span>Status</span><span>Received</span></div>{data.recentRfqs.map((rfq) => <div className="table-row" key={rfq.id}><strong>{rfq.reference}</strong><span>{rfq.company}</span><span className={`status-${rfq.status.toLowerCase()}`}>{rfq.status}</span><span>{new Date(rfq.createdAt).toLocaleString()}</span></div>)}</div> : <p className="admin-empty">No enquiries yet.</p>}</div></div> }
function CollectionView({ title, items, selected, onSelect, onAdd, onDelete, filter, editor, actions }: { title: string; items: Item[]; selected: Item | null; onSelect: (item: Item) => void; onAdd?: () => void; onDelete?: () => void; filter?: React.ReactNode; editor: React.ReactNode; actions: React.ReactNode }) { return <div className="admin-content" aria-label={title} data-can-delete={Boolean(onDelete)}><div className="content-list"><div className="list-heading"><strong>{items.length} records</strong>{filter || (onAdd ? <button onClick={onAdd}><Plus />Add new</button> : null)}</div>{items.map((item) => <button key={item.id} className={selected?.id === item.id ? 'selected' : ''} onClick={() => onSelect(item)}><strong>{String(item.name ?? item.label ?? item.platform ?? item.title ?? item.sectionKey ?? item.reference ?? item.email)}</strong><span>{String(item.status ?? (item.active === false ? 'Disabled' : ''))} #{item.id || 'new'}</span></button>)}</div><div className="content-editor">{editor || <div className="admin-empty">Select or create an item.</div>}{actions ? <div className="editor-actions">{actions}</div> : null}</div></div> }
function SettingsEditor({ value, onChange }: { value: any; onChange: (value: any) => void }) { async function upload(key: 'logoUrl' | 'faviconUrl', file: File) { const form = new FormData(); form.set('file', file); const response = await fetch('/api/admin/media', { method: 'POST', body: form }); if (response.ok) { const asset = await response.json(); onChange({ ...value, [key]: asset.publicUrl }) } } return <div className="admin-content settings-content"><div className="settings-panel"><h1>Site identity</h1><p>Manage the public brand, language defaults and browser icon.</p><div className="logo-preview"><img src={value.logoUrl} alt="Current company logo" /><div><strong>Company logo</strong><span>Upload a JPG, PNG, WebP or AVIF image.</span></div></div><div className="field-grid"><label>Website name<input value={value.siteName} onChange={(e) => onChange({ ...value, siteName: e.target.value })} /></label><label>Chinese site name<input value={value.siteNameZh} onChange={(e) => onChange({ ...value, siteNameZh: e.target.value })} /></label><label>Russian site name<input value={value.siteNameRu} onChange={(e) => onChange({ ...value, siteNameRu: e.target.value })} /></label><label>Default language<select value={value.defaultLocale} onChange={(e) => onChange({ ...value, defaultLocale: e.target.value })}><option value="en">English</option><option value="zh">中文</option><option value="ru">Русский</option></select></label><label>Logo URL<input value={value.logoUrl} onChange={(e) => onChange({ ...value, logoUrl: e.target.value })} /><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload('logoUrl', file) }} /></label><label>Favicon URL<input value={value.faviconUrl || ''} onChange={(e) => onChange({ ...value, faviconUrl: e.target.value })} /><input type="file" accept="image/jpeg,image/png,image/webp,image/avif,.ico" onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload('faviconUrl', file) }} /></label></div></div></div> }
function UserEditor({ item, onChange }: { item: Item; onChange: (item: Item) => void }) { return <div><div className="editor-header"><div><span>{item.id ? `User #${item.id}` : 'New user'}</span><h1>{String(item.name || item.email || 'User')}</h1></div><span className="published-badge">{item.active ? 'Active' : 'Disabled'}</span></div><div className="field-grid"><label>Name<input value={String(item.name || '')} onChange={(e) => onChange({ ...item, name: e.target.value })} /></label><label>Email<input type="email" value={String(item.email || '')} onChange={(e) => onChange({ ...item, email: e.target.value })} /></label><label>Role<select value={String(item.role || 'EDITOR')} onChange={(e) => onChange({ ...item, role: e.target.value })}><option value="ADMIN">Administrator</option><option value="EDITOR">Editor</option><option value="RFQ_OPERATOR">RFQ operator</option></select></label><label>Active<input type="checkbox" checked={Boolean(item.active)} onChange={(e) => onChange({ ...item, active: e.target.checked })} /></label><label>New password<input type="password" value={String(item.password || '')} minLength={10} placeholder={item.id ? 'Leave blank to keep current password' : 'At least 10 characters'} onChange={(e) => onChange({ ...item, password: e.target.value })} /></label></div></div> }
function ItemEditor({ item, onChange }: { item: Item; onChange: (item: Item) => void }) { const label = String(item.name ?? item.label ?? item.platform ?? item.title ?? item.sectionKey ?? item.reference ?? 'Record'); return <div><div className="editor-header"><div><span>Record #{item.id}</span><h1>{label}</h1></div><span className="published-badge">{String(item.status ?? 'Published')}</span></div><div className="field-grid">{Object.entries(item).filter(([key, value]) => key !== 'id' && !key.endsWith('At') && !['attachments', 'internalNotes', 'idempotencyKey', 'consentAt'].includes(key) && typeof value !== 'object').map(([key, value]) => <label key={key}>{key.replace(/([A-Z])/g, ' $1')}{key === 'status' ? <select value={String(value)} onChange={(e) => onChange({ ...item, [key]: e.target.value })}><option>NEW</option><option>IN_REVIEW</option><option>QUOTED</option><option>WON</option><option>LOST</option><option>SPAM</option><option>ARCHIVED</option><option>DRAFT</option><option>PUBLISHED</option></select> : typeof value === 'boolean' ? <input type="checkbox" checked={value} onChange={(e) => onChange({ ...item, [key]: e.target.checked })} /> : imageKeys.has(key) ? <ImageField item={item} field={key} value={String(value || '')} onChange={onChange} /> : key === 'body' || key === 'description' || key === 'notes' || key.endsWith('Zh') || key.endsWith('Ru') ? <textarea rows={4} value={String(value)} onChange={(e) => onChange({ ...item, [key]: e.target.value })} /> : <input type={typeof value === 'number' ? 'number' : 'text'} value={String(value)} onChange={(e) => onChange({ ...item, [key]: typeof value === 'number' ? Number(e.target.value) : e.target.value })} />}</label>)}</div></div> }
function ImageField({ item, field, value, onChange }: { item: Item; field: string; value: string; onChange: (item: Item) => void }) { const [busy, setBusy] = useState(false); async function upload(file: File) { setBusy(true); const form = new FormData(); form.set('file', file); const response = await fetch('/api/admin/media', { method: 'POST', body: form }); if (response.ok) { const asset = await response.json(); onChange({ ...item, [field]: asset.publicUrl }) } setBusy(false) } return <div className="image-field"><input value={value} onChange={(e) => onChange({ ...item, [field]: e.target.value })} /><div className="image-field-actions"><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={busy} onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload(file) }} />{busy && <small>Uploading…</small>}</div>{value && <img className="field-image-preview" src={value} alt="" />}</div> }
function RfqEditor({ item, onChange, onStatus }: { item: Item; onChange: (item: Item) => void; onStatus: (status: string) => void }) { const [note, setNote] = useState(''); const [retrying, setRetrying] = useState(false); async function addNote() { if (!note.trim()) return; const response = await fetch('/api/admin/rfq', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: item.id, internalNote: note }) }); if (response.ok) { onChange(await response.json()); setNote('') } } async function retry() { setRetrying(true); const response = await fetch(`/api/admin/rfq/${item.id}/retry`, { method: 'POST' }); if (response.ok) onChange(await response.json()); onStatus(response.ok ? 'Notification updated' : 'Retry failed'); setRetrying(false) } return <div><div className="editor-header"><div><span>RFQ #{item.id}</span><h1>{String(item.reference)}</h1></div><span className="published-badge">{String(item.status)}</span></div><div className="field-grid"><label>Status<select value={String(item.status)} onChange={(e) => onChange({ ...item, status: e.target.value })}><option>NEW</option><option>IN_REVIEW</option><option>QUOTED</option><option>WON</option><option>LOST</option><option>SPAM</option><option>ARCHIVED</option></select></label><label>Notification status<input value={String(item.notificationStatus || 'PENDING')} readOnly /></label></div><div className="rfq-attachments"><strong>Attachments</strong>{Array.isArray(item.attachments) && item.attachments.length ? item.attachments.map((a: any) => <a key={a.id} href={`/api/admin/rfq/attachment/${a.id}`} target="_blank" rel="noreferrer">{a.originalName}</a>) : <span>No attachments</span>}</div><div className="rfq-notes"><strong>Internal notes</strong>{Array.isArray(item.internalNotes) && item.internalNotes.map((n: any) => <p key={n.id}><b>{n.author?.name || 'Operator'}</b> {n.body}</p>)}<textarea rows={3} value={note} onChange={(e) => setNote(e.target.value)} placeholder="Add an internal note" /><button onClick={addNote}>Add note</button></div><button onClick={retry} disabled={retrying || item.notificationStatus === 'SENT'}>{retrying ? 'Retrying…' : 'Retry notification'}</button></div> }
function AuditView({ data }: { data: any }) { return <div className="audit-content"><div className="panel-heading"><div><span className="admin-eyebrow">Traceability</span><h1>Audit log</h1><p>Every content, settings, user and media change is recorded here.</p></div></div>{data?.items?.length ? <div className="audit-table"><div className="table-row table-head"><span>Time</span><span>Actor</span><span>Action</span><span>Entity</span><span>Summary</span></div>{data.items.map((log: any) => <div className="table-row" key={log.id}><span>{new Date(log.createdAt).toLocaleString()}</span><span>{log.user?.name || 'System'}</span><strong>{log.action}</strong><span>{log.entityType} #{log.entityId}</span><span>{log.summary}</span></div>)}</div> : <div className="admin-empty">No audit entries yet.</div>}</div> }
