import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { prisma } from '@/lib/prisma'
import { locales, parseLocale, type Locale } from '@/lib/i18n'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight } from 'lucide-react'

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale: raw } = await params; const locale = parseLocale(raw); return { title: locale === 'zh' ? '常见问题 | Hocore Biotech' : locale === 'ru' ? 'FAQ | Hocore Biotech' : 'FAQ | Hocore Biotech' } }
export default async function FaqPage({ params }: { params: Promise<{ locale: string }> }) { const { locale: raw } = await params; if (!locales.includes(raw as Locale)) notFound(); const locale = parseLocale(raw); const faqs = await prisma.faq.findMany({ where: { enabled: true }, orderBy: { sortOrder: 'asc' } }); const quote = locale === 'zh' ? '提交询盘' : locale === 'ru' ? 'Запросить предложение' : 'Request a quote'; return <main className="content-page"><header className="site-header"><Link className="brand" href={`/${locale}`}><span className="brand-mark">H</span><span>Hocore<small>biotech</small></span></Link><nav className="main-nav open"><Link href={`/${locale}/products`}>Products</Link><Link href={`/${locale}/solutions`}>Solutions</Link><Link href={`/${locale}/quality`}>Quality</Link><Link href={`/${locale}/resources`}>Resources</Link></nav><Link className="button primary" href={`/${locale}/rfq`}>{quote}<ArrowRight size={16}/></Link></header><section className="page-hero-split"><div className="page-hero-copy"><p className="section-kicker">FAQ</p><h1>{locale === 'zh' ? '关于寻源、文件和交付的常见问题。' : locale === 'ru' ? 'Ответы по поиску, документам и доставке.' : 'Answers about sourcing, documents and delivery.'}</h1><p>{locale === 'zh' ? '了解如何提交型号、确认文件、选择温区以及处理多品牌采购。' : locale === 'ru' ? 'Как отправить позицию, подтвердить документы, выбрать температуру и вести мультибрендовый заказ.' : 'Learn how to submit an item, confirm documents, choose a temperature lane and manage a multi-brand request.'}</p></div><div className="page-hero-media"><Image src="/products/microscopy.jpg" alt="" fill priority sizes="(max-width: 900px) 100vw, 50vw"/></div></section><section className="faq-overlay"><div>{faqs.map((item) => <details key={item.id}><summary>{locale === 'zh' ? item.questionZh || item.question : locale === 'ru' ? item.questionRu || item.question : item.question}</summary><p>{locale === 'zh' ? item.answerZh || item.answer : locale === 'ru' ? item.answerRu || item.answer : item.answer}</p></details>)}</div></section><section className="content-cta"><div><p className="section-kicker">{locale === 'zh' ? '仍有问题？' : locale === 'ru' ? 'ОСТАЛИСЬ ВОПРОСЫ?' : 'STILL HAVE A QUESTION?'}</p><h2>{locale === 'zh' ? '把具体产品或采购清单发给寻源团队。' : locale === 'ru' ? 'Отправьте конкретный продукт или список закупки.' : 'Send the exact product or purchase list to the sourcing desk.'}</h2></div><Link className="button primary" href={`/${locale}/rfq`}>{quote}<ArrowRight size={16}/></Link></section></main> }
