import { redirect } from 'next/navigation'

export default function HomePage() {
  redirect('/en')
  return null
/*
  const [slide, setSlide] = useState(0)
  const [query, setQuery] = useState('')
  const [line, setLine] = useState<'All' | 'Reagents' | 'Consumables'>('All')
  const [menuOpen, setMenuOpen] = useState(false)
  const [paused, setPaused] = useState(false)
  const filtered = useMemo(() => categories.filter((item) => (line === 'All' || item.kind === line) && `${item.title} ${item.detail} ${item.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [line, query])

  useEffect(() => {
    if (paused) return
    const timer = window.setInterval(() => setSlide((current) => (current + 1) % heroSlides.length), 6500)
    return () => window.clearInterval(timer)
  }, [paused])

  const current = heroSlides[slide]
  return <main>
    <header className="site-header">
      <a className="brand" href="#top" aria-label="Hocore Biotech home"><span className="brand-mark">H</span><span>Hocore<small>biotech</small></span></a>
      <nav className={menuOpen ? 'main-nav open' : 'main-nav'}>
        <a href="#products" onClick={() => setMenuOpen(false)}>Products</a><a href="#solutions" onClick={() => setMenuOpen(false)}>Supply Solutions</a><a href="#quality" onClick={() => setMenuOpen(false)}>Quality & Compliance</a><a href="#resources" onClick={() => setMenuOpen(false)}>Resources</a><a href="#about" onClick={() => setMenuOpen(false)}>About</a>
      </nav>
      <div className="header-actions"><div className="locale"><Globe2 size={15} /><button>EN</button><span>/</span><button>中文</button><span>/</span><button>Рус</button></div><a className="social whatsapp" href="https://wa.me/861857548378" target="_blank" rel="noreferrer"><MessageCircle size={16} /> WhatsApp</a><a className="social vk" href="https://vk.com" target="_blank" rel="noreferrer">VK</a></div>
      <button className="menu-button" onClick={() => setMenuOpen((v) => !v)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button>
    </header>
    <section id="top" className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(3,45,36,.9) 0%, rgba(3,45,36,.68) 42%, rgba(3,45,36,.12) 80%), url(${current.image})` }} onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}>
      <div className="hero-inner"><div className="hero-copy"><p className="eyebrow">{current.kicker}</p><h1>{current.title}</h1><p className="hero-text">{current.text}</p><div className="hero-buttons"><a className="button primary" href="#rfq">Request a quote <ArrowRight size={17} /></a><a className="button ghost" href="#products">Explore products</a></div></div><div className="hero-controls"><button onClick={() => setSlide((slide - 1 + heroSlides.length) % heroSlides.length)} aria-label="Previous slide"><ChevronLeft /></button>{heroSlides.map((item, index) => <button key={item.kicker} className={index === slide ? 'dot active' : 'dot'} onClick={() => setSlide(index)} aria-label={`Go to slide ${index + 1}`} />)}<button onClick={() => setSlide((slide + 1) % heroSlides.length)} aria-label="Next slide"><ChevronRight /></button><span>0{slide + 1} / 0{heroSlides.length}</span></div></div>
    </section>
    <section className="quick-paths"><div><p className="section-kicker">START WITH THE RIGHT ROUTE</p><h2>One desk for the products your work depends on.</h2></div><div className="path-grid"><a href="#products"><span className="path-icon mint"><FileText /></span><strong>Research reagents</strong><small>8 categories · enzymes, antibodies, buffers</small><ArrowRight /></a><a href="#products"><span className="path-icon blue"><ShieldCheck /></span><strong>Lab consumables</strong><small>8 categories · cell culture, PCR, filtration</small><ArrowRight /></a><a href="#rfq"><span className="path-icon gold"><Search /></span><strong>Sourcing desk</strong><small>Brand / CAT No. / custom procurement</small><ArrowRight /></a></div></section>
    <section id="products" className="products-section"><div className="section-heading"><div><p className="section-kicker">PRODUCT CAPABILITY</p><h2>16 categories. Thousands of specifications.</h2><p>Browse by workflow, then send the exact item or a complete list to our sourcing team.</p></div><a className="text-link" href="#rfq">Need a specific item? <ArrowRight size={15} /></a></div><div className="catalogue-tools"><div className="search-box"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search category, application or specification" /></div><div className="segmented"><button className={line === 'All' ? 'selected' : ''} onClick={() => setLine('All')}>All</button><button className={line === 'Reagents' ? 'selected' : ''} onClick={() => setLine('Reagents')}>Reagents</button><button className={line === 'Consumables' ? 'selected' : ''} onClick={() => setLine('Consumables')}>Consumables</button></div></div><div className="category-grid">{filtered.map((item, index) => <article className="category-card" key={item.title}><div className={`category-visual ${item.tone}`}><span>0{index + 1}</span><div className="visual-orbit" /><div className="visual-line" /></div><div className="category-body"><div className="category-meta"><span>{item.kind}</span><span>Available to source</span></div><h3>{item.title}</h3><p>{item.detail}</p><div className="tag-row">{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><a href="#rfq">View supply scope <ArrowRight size={14} /></a></div></article>)}</div></section>
    <section className="network-section"><div className="network-copy"><p className="section-kicker">GLOBAL BRAND COVERAGE</p><h2>Reach the right source, wherever it sits.</h2><p>We connect regional brand channels with one procurement conversation and one documented delivery path.</p><div className="network-stat"><strong>4</strong><span>source regions<br />across the global supply network</span></div></div><div className="region-list">{brandRegions.map((item) => <div className={`region-row ${item.color}`} key={item.region}><div className="region-name"><span />{item.region}</div><p>{item.brands}</p><ArrowRight size={16} /></div>)}</div></section>
    <section id="solutions" className="solutions-section"><div className="section-heading"><div><p className="section-kicker">SUPPLY SOLUTIONS</p><h2>Less supplier friction. More continuity.</h2></div><p className="heading-note">From one hard-to-find item to a long-term programme, the same desk stays accountable.</p></div><div className="solution-grid"><article><span>01</span><h3>Consolidated procurement</h3><p>One conversation, one quote and one settlement across a wider catalogue.</p><a href="#rfq">Build a procurement list <ArrowRight size={14} /></a></article><article><span>02</span><h3>Specified sourcing</h3><p>Share brand, CAT No. or full specifications and receive a documented route.</p><a href="#rfq">Start a sourcing request <ArrowRight size={14} /></a></article><article><span>03</span><h3>Alternative selection</h3><p>Compare like-for-like options for discontinued, constrained or high-cost items.</p><a href="#rfq">Talk to a specialist <ArrowRight size={14} /></a></article><article><span>04</span><h3>Distributor programme</h3><p>Trial orders, drop-ship support, tiered pricing and project coordination.</p><a href="#rfq">Explore partnership <ArrowRight size={14} /></a></article></div></section>
    <section id="quality" className="quality-section"><div className="quality-header"><div><p className="section-kicker">QUALITY & COMPLIANCE</p><h2>Evidence at every handover.</h2></div><p>Original-source documentation and temperature-aware delivery built into the procurement path.</p></div><div className="quality-grid"><div className="quality-main"><div className="process-line"><span>Source</span><span>QC</span><span>Pack</span><span>Customs</span><span>Deliver</span></div><h3>Traceable from source to destination.</h3><p>Batch information, COA/TDS/SDS availability and delivery documentation are aligned before dispatch.</p><a className="button dark" href="#resources">Explore quality standards <ArrowRight size={16} /></a></div><div className="quality-proof"><div><Snowflake /><strong>3 temperature lanes</strong><span>Ambient · 2–8°C · -20°C</span></div><div><CircleCheck /><strong>15–25 days</strong><span>Standard delivery to major Russian cities</span></div><div><FileText /><strong>3 business days</strong><span>Specified sourcing response</span></div></div></div></section>
    <section id="resources" className="resources-section"><div className="section-heading"><div><p className="section-kicker">RESOURCES</p><h2>Useful before the order is placed.</h2></div><a className="text-link" href="#rfq">Visit resource center <ArrowRight size={15} /></a></div><div className="resource-grid"><article className="resource-feature"><div className="resource-image lab-image" /><p>PROCUREMENT GUIDE</p><h3>How to send a sourcing request that returns a clear answer.</h3><a href="#rfq">Read guide <ArrowRight size={14} /></a></article><article><p>STORAGE & SHIPPING</p><h3>Choosing the right temperature lane.</h3><span className="resource-line" /><a href="#rfq">Read guide <ArrowRight size={14} /></a></article><article><p>QUALITY DOCUMENTS</p><h3>COA, TDS and SDS: what each file tells you.</h3><span className="resource-line" /><a href="#rfq">Read guide <ArrowRight size={14} /></a></article></div></section>
    <section id="rfq" className="rfq-section"><div><p className="section-kicker">REQUEST FOR QUOTATION</p><h2>Have a brand, CAT No. or purchase list?</h2><p>Send the specification once. We will come back with sourcing options, timing, temperature lane and available documentation.</p></div><RfqForm /></section>
    <footer id="about" className="site-footer"><div className="footer-brand"><a className="brand light" href="#top"><span className="brand-mark">H</span><span>Hocore<small>biotech</small></span></a><p>Global life science sourcing<br />for research teams across Russia.</p></div><div><p className="footer-label">CONTACT</p><a href="mailto:zehongyan2025@outlook.com">zehongyan2025@outlook.com</a><a href="tel:+861857548378">+86 185 7584 8378</a><a href="https://wa.me/861857548378">WhatsApp</a><a href="https://vk.com">VK</a></div><div><p className="footer-label">OFFICE HOURS</p><p>Mon–Fri<br />09:00–18:00 (UTC+8)</p><p className="footer-label">SHENZHEN, CHINA</p></div><div className="footer-legal">Research use only. Product availability, specifications, prices and service terms are subject to the final procurement contract. <span>© 2026 Hocore Biotech</span></div></footer>
  </main>
*/
}
/*
function RfqForm() {
  const [reference, setReference] = useState('')
  const [status, setStatus] = useState<'idle'|'sending'|'error'>('idle')
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus('sending')
    const form = new FormData(event.currentTarget)
    const response = await fetch('/api/rfq',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({company:form.get('company'),email:form.get('email'),brandCatNo:form.get('brandCatNo'),quantity:form.get('quantity'),description:form.get('description')})})
    if (!response.ok) { setStatus('error'); return }
    const data = await response.json(); setReference(data.reference)
  }
  if (reference) return <div className="rfq-success"><CircleCheck size={28} /><h3>Request received.</h3><p>Reference <strong>{reference}</strong> has been created. Our sourcing desk will follow up within 3 business days.</p><a className="button dark" href="#top">Back to homepage</a></div>
  return <form className="rfq-form" onSubmit={submit}><div className="form-row"><label>Company<input name="company" required placeholder="Your organization" /></label><label>Work email<input name="email" required type="email" placeholder="name@company.com" /></label></div><div className="form-row"><label>Brand / CAT No.<input name="brandCatNo" placeholder="Optional" /></label><label>Quantity<input name="quantity" placeholder="Approximate volume" /></label></div><label>Product or specification<textarea name="description" required rows={3} placeholder="Tell us what you need to source" /></label><label className="upload-field"><span>Attach purchase list <small>PDF, XLSX, CSV, DOCX · max 10 MB</small></span><input type="file" accept=".pdf,.xlsx,.xls,.csv,.docx" /></label><label className="consent"><input type="checkbox" required /> I agree to the privacy policy and consent to being contacted about this request.</label>{status==='error'?<p className="form-error">The request could not be saved. Please try WhatsApp or email.</p>:null}<button className="button primary" type="submit" disabled={status==='sending'}>{status==='sending'?'Submitting…':'Submit RFQ'} <ArrowRight size={17} /></button></form>
}
*/
