import type { Locale } from './i18n'

export const siteCopy: Record<Locale, {
  nav: string[]; quote: string; explore: string; hero: [string, string, string];
  quickTitle: string; quick: string[]; productKicker: string; productTitle: string;
  productBody: string; solutionKicker: string; solutionTitle: string; qualityTitle: string;
  resourceTitle: string; rfqTitle: string; rfqBody: string; contact: string; language: string;
}> = {
  en: { nav: ['Products', 'Supply Solutions', 'Quality & Compliance', 'Resources', 'About'], quote: 'Request a quote', explore: 'Explore products', hero: ['Reliable access to research reagents and lab consumables', 'Global brands. One procurement partner. Compliant delivery across Russia.', 'GLOBAL LIFE SCIENCE SOURCING'], quickTitle: 'One desk for the products your work depends on.', quick: ['Research reagents', 'Lab consumables', 'Sourcing desk'], productKicker: 'PRODUCT CAPABILITY', productTitle: '16 categories. Thousands of specifications.', productBody: 'Browse by workflow, then send the exact item or a complete list to our sourcing team.', solutionKicker: 'SUPPLY SOLUTIONS', solutionTitle: 'Less supplier friction. More continuity.', qualityTitle: 'Evidence at every handover.', resourceTitle: 'Useful before the order is placed.', rfqTitle: 'Have a brand, CAT No. or purchase list?', rfqBody: 'Send the specification once. We will come back with sourcing options, timing, temperature lane and available documentation.', contact: 'Contact', language: 'Language' },
  zh: { nav: ['产品中心', '采购服务', '质量与合规', '资源中心', '关于我们'], quote: '提交询盘', explore: '浏览产品', hero: ['可靠获取科研试剂与实验室耗材', '覆盖全球品牌，由一个采购伙伴协调合规交付至俄罗斯。', '全球生命科学供应'], quickTitle: '一个采购窗口，覆盖您实验所依赖的产品。', quick: ['科研试剂', '实验室耗材', '指定寻源'], productKicker: '产品能力', productTitle: '16 个品类，覆盖数千种规格。', productBody: '按实验流程浏览目录，也可以直接提交具体型号或完整采购清单。', solutionKicker: '采购服务', solutionTitle: '减少供应商摩擦，保障持续供货。', qualityTitle: '每一次交接都有依据。', resourceTitle: '在下单前，先获得有用信息。', rfqTitle: '有品牌、CAT No. 或采购清单？', rfqBody: '提交一次规格信息，我们将回复寻源选项、周期、温区和可提供的文件。', contact: '联系方式', language: '语言' },
  ru: { nav: ['Продукты', 'Решения по снабжению', 'Качество и соответствие', 'Ресурсы', 'О компании'], quote: 'Запросить предложение', explore: 'Каталог', hero: ['Надёжный доступ к реагентам и лабораторным расходным материалам', 'Глобальные бренды. Один закупочный партнёр. Документированная доставка по России.', 'ПОСТАВКИ ДЛЯ LIFE SCIENCE'], quickTitle: 'Один контакт для продуктов, от которых зависит ваша работа.', quick: ['Исследовательские реагенты', 'Лабораторные расходные материалы', 'Поиск по запросу'], productKicker: 'КАТАЛОГ', productTitle: '16 категорий. Тысячи спецификаций.', productBody: 'Выберите направление или отправьте точный артикул и полный список на поиск.', solutionKicker: 'РЕШЕНИЯ ПО СНАБЖЕНИЮ', solutionTitle: 'Меньше барьеров поставки. Больше непрерывности.', qualityTitle: 'Подтверждения на каждом этапе.', resourceTitle: 'Полезно до оформления заказа.', rfqTitle: 'Есть бренд, CAT No. или список закупки?', rfqBody: 'Отправьте спецификацию. Мы вернём варианты поставки, сроки, температурный режим и доступные документы.', contact: 'Контакты', language: 'Язык' }
}
