const labels: Record<string, string> = {
  '科研试剂': 'Research Reagents', '实验室耗材': 'Laboratory Consumables',
  '分子生物学试剂': 'Molecular Biology Reagents', '细胞培养与细胞生物学试剂': 'Cell Culture & Cell Biology Reagents', '蛋白质与生物化学试剂': 'Protein & Biochemistry Reagents', '抗体与免疫学试剂': 'Antibody & Immunology Reagents', '细胞因子与生长因子': 'Cytokines & Growth Factors', '微生物培养与鉴定试剂': 'Microbiology Culture & Identification Reagents', '染色与显色试剂': 'Staining & Detection Reagents', '缓冲液与常用溶液': 'Buffers & Common Solutions',
  '通用实验室耗材': 'General Laboratory Consumables', '细胞培养耗材': 'Cell Culture Consumables', '分子生物学耗材': 'Molecular Biology Consumables', '蛋白与生化实验耗材': 'Protein & Biochemistry Consumables', '微生物与病理耗材': 'Microbiology & Histopathology Consumables', '过滤与色谱耗材': 'Filtration & Chromatography Consumables', '样本采集与存储耗材': 'Sample Collection & Storage Consumables', '仪器配件与维护耗材': 'Instrument Accessories & Maintenance Consumables', '安全防护与动物实验耗材': 'Safety & Animal Research Consumables',
  'PCR与qPCR试剂': 'PCR & qPCR Reagents', '逆转录与cDNA合成': 'Reverse Transcription & cDNA Synthesis', '核酸扩增与克隆': 'Nucleic Acid Amplification & Cloning', '核酸提取与纯化': 'Nucleic Acid Extraction & Purification', '核酸标记与检测': 'Nucleic Acid Labelling & Detection', '基因编辑试剂': 'Gene Editing Reagents', '测序与NGS试剂': 'Sequencing & NGS Reagents', '分子生物学专用酶': 'Molecular Biology Enzymes',
  '细胞培养基': 'Cell Culture Media', '胎牛血清与血清替代': 'Fetal Bovine Serum & Replacements', '细胞培养添加物': 'Cell Culture Supplements', '细胞消化与解离试剂': 'Cell Dissociation & Detachment Reagents', '细胞冻存与复苏': 'Cell Cryopreservation & Recovery', '细胞增殖与毒性检测': 'Cell Proliferation & Cytotoxicity Assays', '细胞凋亡与周期检测': 'Apoptosis & Cell Cycle Assays', '干细胞与类器官培养': 'Stem Cell & Organoid Culture',
  '蛋白提取与裂解试剂': 'Protein Extraction & Lysis', '蛋白定量试剂': 'Protein Quantification', '蛋白电泳试剂': 'Protein Electrophoresis', '蛋白转膜与封闭试剂': 'Western Blot Transfer & Blocking', '酶与辅酶': 'Enzymes & Coenzymes', '生化试剂与小分子': 'Biochemical Reagents & Small Molecules', '蛋白结晶与结构生物学': 'Protein Crystallization & Structural Biology',
  '一抗': 'Primary Antibodies', '二抗': 'Secondary Antibodies', 'ELISA试剂盒': 'ELISA Kits', '免疫组化（IHC）试剂': 'Immunohistochemistry (IHC)', '免疫荧光（IF）试剂': 'Immunofluorescence (IF)', '流式细胞术试剂': 'Flow Cytometry Reagents',
  '重组细胞因子': 'Recombinant Cytokines', '生长因子': 'Growth Factors', '趋化因子': 'Chemokines', '激素与调节肽': 'Hormones & Regulatory Peptides', '细菌培养基': 'Bacterial Culture Media', '真菌与酵母培养基': 'Fungal & Yeast Culture Media', '细胞培养用支原体检测': 'Mycoplasma Detection', '微生物鉴定试剂': 'Microbial Identification', '抗生素与抗真菌剂（微生物用）': 'Antibiotics & Antifungals',
  '核酸染色试剂': 'Nucleic Acid Stains', '蛋白染色试剂': 'Protein Stains', '细胞染色试剂': 'Cell Stains', '免疫显色试剂': 'Immunohistochemistry Substrates', '组织病理染色试剂': 'Histopathology Stains', '分子生物学缓冲液': 'Molecular Biology Buffers', '细胞培养缓冲液': 'Cell Culture Buffers', '蛋白实验缓冲液': 'Protein Assay Buffers', '免疫检测缓冲液': 'Immunoassay Buffers', '常用盐溶液与化学试剂': 'Common Salts & Chemicals',
  '移液器吸头': 'Pipette Tips', '离心管与PCR管': 'Microcentrifuge & PCR Tubes', '试管与样品管': 'Test & Sample Tubes', '量筒与容量瓶': 'Graduated Cylinders & Volumetric Flasks', '移液管与滴管': 'Serological Pipettes & Droppers', '标签与记号笔': 'Labels & Lab Markers', '封口膜与称量耗材': 'Sealing Film & Weighing Supplies', '细胞培养瓶': 'Cell Culture Flasks', '细胞培养板': 'Cell Culture Plates', '细胞培养皿': 'Cell Culture Dishes', '细胞工厂与生物反应器': 'Cell Factories & Bioreactors', '3D培养与类器官耗材': '3D Culture & Organoid Supplies', '细胞刮刀与细胞处理耗材': 'Cell Scrapers & Handling Supplies',
  'PCR与qPCR耗材': 'PCR & qPCR Consumables', '核酸电泳耗材': 'Nucleic Acid Electrophoresis', '克隆与转化耗材': 'Cloning & Transformation Supplies', '核酸纯化专用耗材': 'Nucleic Acid Purification Supplies', '蛋白电泳耗材': 'Protein Electrophoresis Supplies', '蛋白纯化耗材': 'Protein Purification Supplies', '酶标板与ELISA耗材': 'Microplates & ELISA Supplies', '蛋白样品制备耗材': 'Protein Sample Preparation', '微生物培养耗材': 'Microbiology Culture Supplies', '组织取材与固定耗材': 'Tissue Collection & Fixation', '石蜡切片与染色耗材': 'Paraffin Sectioning & Staining', '冰冻切片耗材': 'Frozen Section Supplies',
  '针头式过滤器': 'Syringe Filters', '真空过滤装置': 'Vacuum Filtration', '色谱分析耗材': 'Chromatography Supplies', '超滤与透析耗材': 'Ultrafiltration & Dialysis', '血液采集耗材': 'Blood Collection Supplies', '生物样本采集耗材': 'Biological Sample Collection', '冻存管与冻存盒': 'Cryovials & Cryoboxes', '低温存储耗材': 'Cold Storage Supplies', '样本运输耗材': 'Sample Transport Supplies', '移液器配件与校准': 'Pipette Accessories & Calibration', '离心机配件与转子': 'Centrifuge Accessories & Rotors', 'PCR仪/测序仪配件': 'PCR & Sequencer Accessories', '仪器清洁与维护耗材': 'Instrument Cleaning & Maintenance', '个人防护装备（PPE）': 'Personal Protective Equipment (PPE)', '生物安全耗材': 'Biosafety Supplies', '动物饲养耗材': 'Animal Housing Supplies', '动物实验操作耗材': 'Animal Research Supplies'
}

export function productCategoryLabel(name: string, locale: 'en' | 'zh' | 'ru') {
  if (locale === 'zh') return name
  return labels[name] || name
}
